#!/usr/bin/env bash
#install Nginx web server


sudo apt-get update
sudo apt-get -y install nginx
sudo rm /var/www/html/*
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
