#!/usr/bin/env bash
#install Nginx web server

SU=$(whoami)
TMP_FILE="tmp_version"

if [[ "$SU" == "root" ]];
then
	SU="sudo"
else
	SU=""
fi

$SU apt-get update
$SU apt-get -y install nginx

nginx -v 2> "$TMP_FILE" 1> /dev/null

if [[ "$(wc --lines --$TMP_FILE | cut --fields=1 --delimiter=" ")" -eq 1 ]];
then
	$SU rm /var/www/html/*
	$SU echo "Hello World" | sudo tee /var/www/html/index.html
	$SU service nginx restart
fi
$SU rm "$TMP_FILE"
