#!/usr/bin/env bash
# Script that configures a load balancer for Ubuntu 20.04
sudo apt-get update
sudo apt-get install -y haproxy
sudo chown -R ubuntu /etc/haproxy
sudo chown -R ubuntu /etc/default

configuration="\

frontend http
	bind *: 80
	mode http
	default_backend web-server

backend web-server
	balance roundrobin
	server 3014-web-01 35.237.96.82:80 check
	server 3014-web-02 54.164.136.88:80 check
"

echo "$configuration" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
