#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

filename="/var/run/myscript.pid"
echo "$$" > filename
trap "echo 'I hate the kill command'; rm -rf filename; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf filename; exit" SIGQUIT
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
