#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
LIMIT=10
i=1
while [ "$i" -le "$LIMIT" ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
