#!/usr/bin/env bash
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
LIMIT=20
i=1
while [ "$i" -le "$LIMIT" ]
do
	echo "$i"
	case "$i" in
		4*)
		echo "bad luck from China"
		;;
		9*)
		echo "bad luck from Japan"
		;;
		17*)
		echo "bad luck from Italy"
		;;
	esac
	((i+=1))
done
