#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59
LIMIT=59
i=1
while [ "$i" -le "$LIMIT" ]
do
	echo "$i"
	((i+=1))
done
echo "Hour: 1"
number=9
i=1
while [ "$i" -le "$number" ]
do
	echo "$i"
	((i+=1))
done
