#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59
MINUTES=59
HOUR=12
i=0
while [ "$i" -le "$HOUR" ]
do
	echo "Hour: $i"
	j=1
	while [ "$j" -le "$MINUTES" ]
	do
		echo "$j"
		((j+=1))
	done
	((i+=1))
done
