#!/usr/bin/env bash
# less scriptto fix bug
pkill -9 apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "1i user nginx;" /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
